@HostAddress = http://localhost:5279

GET {{HostAddress}}/api/products
Accept: application/json
Authorization: Bearer eyJhbGciOiJodHRwOi8vd3d3LnczLm9yZy8yMDAxLzA0L3htbGRzaWctbW9yZSNobWFjLXNoYTI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1lIjoibGljYW51IiwiZXhwIjoxNzc3Mzg3MTQwLCJpc3MiOiJBdXRvbWF0aW9uRXhlcmNpc2VBUEkiLCJhdWQiOiJBdXRvbWF0aW9uRXhlcmNpc2VBUEkifQ.Jev9yr8nk2rCB8BMktHQF84KQxQwsls83EEhP-5twqI