@HostAddress = http://localhost:5279

GET {{HostAddress}}/api/products
Accept: application/json
Authorization: Bearer eyJhbGciOiJodHRwOi8vd3d3LnczLm9yZy8yMDAxLzA0L3htbGRzaWctbW9yZSNobWFjLXNoYTI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1lIjoibGljYW51MSIsImV4cCI6MTc3Nzk5NjA1NCwiaXNzIjoiQXV0b21hdGlvbkV4ZXJjaXNlQVBJIiwiYXVkIjoiQXV0b21hdGlvbkV4ZXJjaXNlQVBJIn0.QbuzQQQ9MirJJA8S6isMcSjSFx0aqkRogHP_bH19l9I